project:
  type: website
  output-dir: docs
  
website:
  title: "Enrico Turletti"
  favicon: et_favicon.png
  open-graph:
    locale: "it"
    site-name: "Enrico Turletti"
    description: "Enrico Turletti is an artist interested in ecological art and postmedia practices. He has a transdisciplinary approach that moves through posthuman philosophy, computer science, visual and sound."
    image: "et_favicon.png"
  sidebar: 
    style: "floating"
    alignment: center
    search: false
    contents: auto
    tools:
      - icon: instagram
        href: https://instagram.com/enrico_turletti/
format:
  html:
    theme: 
      - solar
      - custom.scss
    mainfont: Tahoma
    toc: false
filters: 
  - externalink.lua



