---
title: "Bio"
lang: en
link-external-newwindow: true
toc: true
toc-title: "Toc"
---
<div class="navbar">
  <div class="index-logo"><a href="index.html">Enrico Turletti</a></div>
  <div class="other-links">
  <a href="#">Bio</a>
  <a href="contacts.html">Contacts</a>
  <a href="exhibitions.html">Works</a>
  <a href="music.html">Music</a>
  <hr>
  </div>
</div>
Enrico Turletti graduated in New Technologies of Art from the Albertina Academy of Fine Arts in Turin.
His work explores the relationship between human beings and the world, and the formation of human consciousness through technology.<br>
With a transdisciplinary approach, he moves between art, computer science, posthuman philosophy, visual culture, and sound. Through speculative fictions, he creates spaces where the human and the more-than-human intertwine in unexpected ways.<br>
His works have been presented at various international festivals and venues, including the Italian Cultural Institute in Madrid, Milano Music Week, and Cape Town Art Week. One of his artist’s books is part of the Interspecies Library archive in New York.

<h3>Exhibitions</h3>
<hr>
<ul class="aos-ul">
<li>Investec Cape Town Art Fair, Cape Town, South Africa</li>
<li>Milano Music Week, Linea, Milan, Italy</li>
<li>TO.BE III, Ghëddo, Turin, Italy</li>
<li>Materie, Osservatorio Futura, Turin, Italy</li>
<li>Spring Rolls, Lavanderia a Vapore, Turin, Italy</li>
</ul>

<h3>AOS</h3>
<hr>
<ul class="aos-ul">
<li>New Media Art</li>
<li>Sci-Art</li>
<li>Postmedia Art</li>
<li>Posthuman Theory</li>
</ul>

<h3>Academic background</h3>
<hr>
<ul class="aos-ul">
<li>*Master's degree in New Technology of Arts*, Albertina Academy of Fine Arts of Turin, Turin, Italy [2020-2023]</li>
<li>*Bachelor's degree in Discipline of Arts, Music and Entertainment*, University of Turin, Turin, Italy [2017-2020]</li>
</ul>
